import { Product, Service, Testimonial, Partner, Project } from "@/types"

export const products: Product[] = [
  {
    id: "1",
    name: "Casement Windows",
    description:
      "Premium casement windows with superior energy efficiency and modern aesthetics. These windows open outward with a crank mechanism, providing excellent ventilation and unobstructed views. Available in vinyl, aluminum, and wood frames with multiple glass options including double and triple pane configurations.",
    shortDescription:
      "Energy-efficient casement windows with modern design and superior ventilation.",
    category: "residential",
    subcategory: "Windows",
    images: ["/images/products/casement-3.jpg", "/images/products/casement-1.jpg", "/images/products/casement-2.jpg"],
    features: [
      "Energy Star certified",
      "Multi-point locking system",
      "Low-E glass coating",
      "Argon gas filled",
      "Custom sizes available",
      "Multiple frame colors",
    ],
    specifications: {
      "Frame Material": "Vinyl / Aluminum / Wood",
      "Glass Type": "Double or Triple Pane",
      "U-Factor": "0.25 - 0.30",
      "Energy Rating": "Energy Star Certified",
      "Max Width": '48"',
      "Max Height": '72"',
    },
    priceRange: { min: 350, max: 1200 },
    isCustomizable: true,
    isFeatured: true,
    tags: ["energy-efficient", "ventilation", "residential"],
  },
  {
    id: "2",
    name: "Sliding Patio Doors",
    description:
      "Elegant sliding patio doors that bring the outdoors in with expansive glass panels. Smooth gliding operation on premium rollers with multi-point locking for security. Perfect for connecting living spaces to patios, decks, and gardens.",
    shortDescription:
      "Smooth-gliding patio doors with expansive glass for seamless indoor-outdoor living.",
    category: "residential",
    subcategory: "Doors",
    images: ["/images/products/sliding-door-1.jpg", "/images/products/sliding-door-2.jpg", "/images/products/sliding-door-3.jpg"],
    features: [
      "Smooth gliding operation",
      "Multi-point lock system",
      "Thermal break technology",
      "Impact-resistant glass option",
      "Built-in blinds available",
      "Pet door compatible",
    ],
    specifications: {
      "Frame Material": "Vinyl / Aluminum",
      "Glass Type": "Double Pane Tempered",
      "Panel Options": "2-panel, 3-panel, 4-panel",
      "Standard Width": '60" - 144"',
      "Standard Height": '80" - 96"',
      "Track System": "Premium Roller System",
    },
    priceRange: { min: 800, max: 3500 },
    isCustomizable: true,
    isFeatured: true,
    tags: ["patio", "sliding", "residential"],
  },
  {
    id: "3",
    name: "Commercial Storefront System",
    description:
      "Professional-grade storefront glazing systems designed for commercial buildings. Featuring durable aluminum framing and high-performance glass, these systems create stunning first impressions while meeting all building codes and energy requirements.",
    shortDescription:
      "Professional storefront glazing with aluminum framing for commercial buildings.",
    category: "commercial",
    subcategory: "Storefront",
    images: ["/images/products/storefront-1.jpg", "/images/products/storefront-2.jpg"],
    features: [
      "Thermally broken frames",
      "Structural silicone glazing",
      "ADA compliant doors",
      "Hurricane impact rated options",
      "Custom finishes",
      "Integrated door systems",
    ],
    specifications: {
      "Frame Material": "Aluminum 6063-T6",
      "Glass Thickness": '1/4" - 1"',
      "Thermal Performance": "U-Factor 0.35",
      "Wind Load": "Up to 80 PSF",
      "Finish Options": "Anodized / Painted / Custom",
      "Code Compliance": "ASTM, AAMA, NFRC",
    },
    priceRange: { min: 5000, max: 25000 },
    isCustomizable: true,
    isFeatured: true,
    tags: ["storefront", "commercial", "aluminum"],
  },
  {
    id: "4",
    name: "Curtain Wall System",
    description:
      "State-of-the-art curtain wall systems for modern commercial and high-rise buildings. Non-structural cladding that provides weather resistance, thermal insulation, and architectural beauty. Engineered for performance and aesthetics.",
    shortDescription:
      "Advanced curtain wall glazing for modern commercial architecture.",
    category: "commercial",
    subcategory: "Curtain Wall",
    images: ["/images/products/curtainwall-1.jpg", "/images/products/curtainwall-2.jpg", "/images/products/curtainwall-3.jpg"],
    features: [
      "Unitized or stick-built options",
      "Superior weather resistance",
      "Acoustic insulation",
      "Solar control glass",
      "Seismic performance rated",
      "BIM models available",
    ],
    specifications: {
      "System Type": "Unitized / Stick-Built",
      "Frame Material": "Aluminum 6063-T6",
      "Glass Options": "Insulated / Laminated / Spandrel",
      "Air Infiltration": "0.06 CFM/ft²",
      "Water Resistance": "15 PSF",
      "Structural Deflection": "L/175",
    },
    priceRange: { min: 15000, max: 100000 },
    isCustomizable: true,
    isFeatured: false,
    tags: ["curtain-wall", "high-rise", "commercial"],
  },
  {
    id: "5",
    name: "Industrial Safety Glass",
    description:
      "Heavy-duty safety door systems for industrial environments. Impact-resistant, fire-rated, and available in various configurations to meet the demanding requirements of factories, warehouses, and processing facilities.",
    shortDescription:
      "Impact-resistant safety glass for demanding industrial environments.",
    category: "industrial",
    subcategory: "Safety Glass",
    images: ["/images/products/safety-glass-1.jpg", "/images/products/safety-glass-2.jpg"],
    features: [
      "Impact resistant",
      "Fire-rated options (60-120 min)",
      "Blast resistant configurations",
      "Chemical resistant coatings",
      "Wire glass available",
      "Custom thicknesses",
    ],
    specifications: {
      "Glass Type": "Tempered / Laminated / Wired",
      "Thickness Range": '1/4" - 1-1/2"',
      "Fire Rating": "Up to 120 minutes",
      "Impact Rating": "CPSC 16 CFR 1201",
      "Max Size": '72" x 120"',
      "Coating Options": "Anti-scratch / Chemical-resistant",
    },
    priceRange: { min: 200, max: 5000 },
    isCustomizable: true,
    isFeatured: false,
    tags: ["safety", "industrial", "fire-rated"],
  },
  {
    id: "6",
    name: "Double Hung Windows",
    description:
      "Classic double hung windows combining timeless style with modern performance. Both sashes tilt in for easy cleaning. Available in a wide range of grid patterns and colors to complement any architectural style.",
    shortDescription:
      "Classic double hung windows with tilt-in sashes for easy maintenance.",
    category: "residential",
    subcategory: "Windows",
    images: ["/images/products/double-hung-1.jpg", "/images/products/double-hung-2.jpg", "/images/products/double-hung-3.jpg"],
    features: [
      "Tilt-in sashes for easy cleaning",
      "Full weatherstripping",
      "Optional grilles and grids",
      "Dual-pane insulated glass",
      "Integral lift rail",
      "Multiple color options",
    ],
    specifications: {
      "Frame Material": "Vinyl / Wood / Composite",
      "Glass Type": "Double Pane Low-E",
      "Operation": "Dual Tilt-In",
      "Standard Widths": '24" - 48"',
      "Standard Heights": '36" - 72"',
      "Grid Options": "Colonial / Prairie / Custom",
    },
    priceRange: { min: 250, max: 900 },
    isCustomizable: true,
    isFeatured: true,
    tags: ["classic", "easy-clean", "residential"],
  },
  {
    id: "7",
    name: "Industrial Overhead Doors",
    description:
      "High-performance overhead doors with glass panels for industrial facilities. Designed for frequent use with heavy-duty hardware and insulated sections. Full-view glass options available for modern industrial aesthetics.",
    shortDescription:
      "Heavy-duty overhead doors with glass panels for industrial facilities.",
    category: "industrial",
    subcategory: "Doors",
    images: ["/images/products/overhead-door-1.jpg", "/images/products/overhead-door-2.jpg"],
    features: [
      "Heavy-duty construction",
      "Insulated sections available",
      "Full-view glass panels",
      "High-cycle springs",
      "Wind load rated",
      "Motorized operation",
    ],
    specifications: {
      "Door Type": "Sectional / Rolling",
      "Material": "Steel / Aluminum with Glass",
      "Insulation": "R-6 to R-18",
      "Max Width": '24\'',
      "Max Height": '16\'',
      "Wind Load": "Up to 50 PSF",
    },
    priceRange: { min: 3000, max: 15000 },
    isCustomizable: true,
    isFeatured: false,
    tags: ["overhead", "industrial", "heavy-duty"],
  },
  {
    id: "8",
    name: "Commercial Entry Systems",
    description:
      "Sophisticated commercial entry door systems featuring tempered glass, automatic operators, and ADA-compliant hardware. Create a welcoming entrance that reflects your business's professional image.",
    shortDescription:
      "Professional entry door systems with automatic operation for commercial spaces.",
    category: "commercial",
    subcategory: "Entry Systems",
    images: ["/images/products/commercial-entry-1.jpg", "/images/products/commercial-entry-2.jpg"],
    features: [
      "Automatic door operators",
      "ADA compliant",
      "Tempered safety glass",
      "Panic hardware ready",
      "Access control compatible",
      "Energy-efficient design",
    ],
    specifications: {
      "Frame Material": "Aluminum / Steel",
      "Glass Type": "Tempered / Laminated",
      "Door Width": '36" - 48" per leaf',
      "Door Height": '84" - 96"',
      "Operation": "Manual / Automatic / Revolving",
      "Hardware": "Commercial Grade 1",
    },
    priceRange: { min: 2500, max: 12000 },
    isCustomizable: true,
    isFeatured: true,
    tags: ["entry", "automatic", "commercial"],
  },
]

export const services: Service[] = [
  {
    id: "1",
    name: "Free Consultation",
    description:
      "Start your project with a complimentary consultation. Our experts will discuss your vision, assess your needs, and recommend the best solutions for your space. Available in-person or via video call.",
    icon: "MessageSquare",
    type: "consultation",
    features: [
      "No-obligation assessment",
      "Expert recommendations",
      "In-person or virtual options",
      "Project timeline overview",
      "Budget guidance",
    ],
    estimatedDuration: "30-60 minutes",
  },
  {
    id: "2",
    name: "On-Site Measurement",
    description:
      "Our certified technicians visit your location to take precise measurements ensuring a perfect fit. We use laser measuring technology for accuracy down to 1/16 of an inch.",
    icon: "Ruler",
    type: "measurement",
    features: [
      "Laser precision measuring",
      "Certified technicians",
      "Same-day scheduling available",
      "Digital measurement reports",
      "Photo documentation",
    ],
    estimatedDuration: "1-2 hours",
  },
  {
    id: "3",
    name: "Professional Installation",
    description:
      "Our experienced installation team ensures your windows and doors are installed correctly, efficiently, and to the highest standards. All installations come with our satisfaction guarantee.",
    icon: "Wrench",
    type: "installation",
    features: [
      "Licensed & insured installers",
      "Clean-up included",
      "Warranty on workmanship",
      "Code compliant installation",
      "Post-installation inspection",
    ],
    estimatedDuration: "Half day - Multiple days",
  },
  {
    id: "4",
    name: "Site Inspection",
    description:
      "Comprehensive on-site inspection to evaluate existing windows, identify issues, and assess the scope of replacement or repair needs. Detailed reports provided.",
    icon: "Search",
    type: "inspection",
    features: [
      "Detailed condition assessment",
      "Energy efficiency evaluation",
      "Code compliance review",
      "Written inspection report",
      "Repair vs. replace recommendations",
    ],
    estimatedDuration: "1-3 hours",
  },
  {
    id: "5",
    name: "Custom Fabrication",
    description:
      "Need something unique? We offer custom glass cutting, shaping, and fabrication to meet your exact specifications. From decorative glass to specialty shapes, we can create it.",
    icon: "Sparkles",
    type: "custom",
    features: [
      "Custom shapes & sizes",
      "Decorative glass options",
      "Specialty coatings",
      "CAD design support",
      "Prototype development",
    ],
    estimatedDuration: "2-4 weeks",
  },
  {
    id: "6",
    name: "Repair & Maintenance",
    description:
      "Keep your windows and doors in optimal condition with our repair and maintenance services. From seal replacements to hardware repairs, we handle it all.",
    icon: "Settings",
    type: "repair",
    features: [
      "Seal replacement",
      "Hardware repair",
      "Glass replacement",
      "Weather stripping",
      "Emergency service available",
    ],
    estimatedDuration: "1-4 hours",
  },
]

export const testimonials: Testimonial[] = [
  {
    id: "1",
    name: "Sarah Mitchell",
    role: "Homeowner",
    content:
      "VERREX transformed our home with beautiful new windows. The team was professional from the initial consultation through installation. Our energy bills have dropped significantly!",
    rating: 5,
  },
  {
    id: "2",
    name: "James Rodriguez",
    role: "Property Manager",
    company: "Pinnacle Properties",
    content:
      "We've used VERREX for multiple commercial projects. Their storefront systems are top-quality and their installation team is the best in the business. Highly recommend for any commercial glazing needs.",
    rating: 5,
  },
  {
    id: "3",
    name: "Emily Chen",
    role: "Architect",
    company: "Chen & Associates",
    content:
      "As an architect, I'm very particular about the products I specify. VERREX consistently delivers high-quality window and door solutions that meet our design requirements and exceed performance expectations.",
    rating: 5,
  },
  {
    id: "4",
    name: "Michael Thompson",
    role: "Factory Manager",
    company: "Thompson Manufacturing",
    content:
      "The industrial safety glass VERREX installed in our facility has been outstanding. Their team understood our safety requirements and delivered a solution that keeps our workers protected.",
    rating: 5,
  },
]

export const partners: Partner[] = [
  {
    id: "1",
    name: "PremiumGlass Inc.",
    logo: "/images/partners/partner-1.svg",
    description: "Leading manufacturer of high-performance glass products.",
    website: "#",
    type: "manufacturer",
  },
  {
    id: "2",
    name: "AlumTech Systems",
    logo: "/images/partners/partner-2.svg",
    description: "Premium aluminum framing and extrusion specialists.",
    website: "#",
    type: "supplier",
  },
  {
    id: "3",
    name: "EcoFrame Solutions",
    logo: "/images/partners/partner-3.svg",
    description: "Sustainable window frame manufacturing.",
    website: "#",
    type: "manufacturer",
  },
]

export const appointmentTimeSlots = [
  "9:00 AM",
  "9:30 AM",
  "10:00 AM",
  "10:30 AM",
  "11:00 AM",
  "11:30 AM",
  "1:00 PM",
  "1:30 PM",
  "2:00 PM",
  "2:30 PM",
  "3:00 PM",
  "3:30 PM",
  "4:00 PM",
]

export const projects: Project[] = [
  {
    id: "1",
    title: "Lakeside Luxury Residence",
    description: "Complete window replacement for a 5,000 sq ft lakefront property. Installed 32 custom casement and picture windows with triple-pane glass for maximum energy efficiency and noise reduction. The project included custom-matched wood interior trim and exterior aluminum cladding in a bronze finish.",
    shortDescription: "Full window replacement for a premium lakefront estate with custom triple-pane glass.",
    category: "residential",
    client: "The Morrison Family",
    location: "Muskoka, Ontario",
    completionDate: "2025-11",
    duration: "3 weeks",
    productsUsed: ["Casement Windows", "Double Hung Windows"],
    squareFootage: "5,000 sq ft",
    images: ["/images/projects/lakeside-1.jpg", "/images/projects/lakeside-2.jpg"],
    tags: ["luxury", "lakefront", "energy-efficient", "custom"],
    isFeatured: true,
    testimonial: {
      quote: "VERREX transformed our lake house. The new windows are stunning and our heating bills dropped by 40%.",
      author: "Robert Morrison",
      role: "Homeowner"
    }
  },
  {
    id: "2",
    title: "Pinnacle Tower Storefront",
    description: "Design and installation of a complete commercial storefront system for a 12-story mixed-use building in downtown Toronto. The project featured thermally-broken aluminum framing, structural glazing, and integrated automatic entry systems. Completed on schedule despite challenging urban logistics.",
    shortDescription: "Full commercial storefront and entry system for a landmark downtown tower.",
    category: "commercial",
    client: "Pinnacle Properties Inc.",
    location: "Toronto, Ontario",
    completionDate: "2025-09",
    duration: "6 weeks",
    productsUsed: ["Commercial Storefront System", "Commercial Entry Systems"],
    squareFootage: "8,500 sq ft glass",
    images: ["/images/projects/pinnacle-1.jpg", "/images/projects/pinnacle-2.jpg"],
    tags: ["storefront", "high-rise", "downtown", "automatic-doors"],
    isFeatured: true,
    testimonial: {
      quote: "The VERREX team delivered a world-class storefront that sets our building apart. Professional from start to finish.",
      author: "James Rodriguez",
      role: "Property Manager, Pinnacle Properties"
    }
  },
  {
    id: "3",
    title: "Heritage Home Restoration",
    description: "Meticulous restoration of original-style windows in a heritage-designated Victorian home. Created custom wood-frame double hung windows with period-accurate grid patterns while incorporating modern Low-E glass and weatherstripping for 21st-century performance.",
    shortDescription: "Period-accurate window restoration for a heritage Victorian home with modern performance.",
    category: "residential",
    client: "Dr. Elena Vasquez",
    location: "Kingston, Ontario",
    completionDate: "2025-07",
    duration: "4 weeks",
    productsUsed: ["Double Hung Windows"],
    squareFootage: "3,200 sq ft",
    images: ["/images/projects/heritage-1.jpg", "/images/projects/heritage-2.jpg"],
    tags: ["heritage", "restoration", "victorian", "custom-grilles"],
    isFeatured: true,
    testimonial: {
      quote: "They preserved the character of our 1890s home while making it comfortable for modern living. True craftsmen.",
      author: "Dr. Elena Vasquez",
      role: "Homeowner"
    }
  },
  {
    id: "4",
    title: "AutoTech Manufacturing Facility",
    description: "Comprehensive safety glass installation for a 45,000 sq ft automotive parts manufacturing plant. Installed fire-rated glass partitions, blast-resistant observation windows, and industrial overhead doors with full-view glass panels. All installations met strict OSHA and Ontario Building Code requirements.",
    shortDescription: "Industrial safety glass and fire-rated partitions for a major manufacturing plant.",
    category: "industrial",
    client: "AutoTech Manufacturing",
    location: "Oshawa, Ontario",
    completionDate: "2025-06",
    duration: "5 weeks",
    productsUsed: ["Industrial Safety Glass", "Industrial Overhead Doors"],
    squareFootage: "45,000 sq ft",
    images: ["/images/projects/autotech-1.jpg", "/images/projects/autotech-2.jpg"],
    tags: ["safety-glass", "fire-rated", "manufacturing", "industrial"],
    isFeatured: false,
    testimonial: {
      quote: "Safety is our top priority. VERREX delivered door systems that exceed our safety requirements.",
      author: "Michael Thompson",
      role: "Factory Manager"
    }
  },
  {
    id: "5",
    title: "Skyline Office Complex",
    description: "Designed and installed a unitized curtain wall system for a new 8-story office complex. The project featured solar control glass, acoustic insulation panels, and a dramatic double-height lobby glazing. BIM coordination ensured seamless integration with the building envelope.",
    shortDescription: "Modern curtain wall system for a prestigious 8-story office development.",
    category: "commercial",
    client: "Skyline Developments",
    location: "Mississauga, Ontario",
    completionDate: "2025-04",
    duration: "10 weeks",
    productsUsed: ["Curtain Wall System", "Commercial Entry Systems"],
    squareFootage: "22,000 sq ft glass",
    images: ["/images/projects/skyline-1.jpg", "/images/projects/skyline-2.jpg"],
    tags: ["curtain-wall", "office", "high-performance", "BIM"],
    isFeatured: true,
  },
  {
    id: "6",
    title: "Riverside Condo Conversions",
    description: "Window and patio door replacement across 48 units in a riverside condominium complex. Coordinated with the condo board and residents for minimal disruption. Each unit received custom-sized sliding patio doors and energy-efficient casement windows.",
    shortDescription: "Multi-unit window & patio door upgrade for a 48-unit riverside condominium.",
    category: "residential",
    client: "Riverside Condo Corp. #412",
    location: "Ottawa, Ontario",
    completionDate: "2025-03",
    duration: "8 weeks",
    productsUsed: ["Sliding Patio Doors", "Casement Windows"],
    squareFootage: "48 units",
    images: ["/images/projects/riverside-1.jpg", "/images/projects/riverside-2.jpg"],
    tags: ["multi-unit", "condo", "patio-doors", "bulk-project"],
    isFeatured: false,
  },
  {
    id: "7",
    title: "Craft Brewery Showcase",
    description: "Custom glass installation for a craft brewery taproom and production facility. Featured a dramatic floor-to-ceiling glass wall separating the brewing area from the tasting room, giving patrons a full view of the brewing process while maintaining climate control.",
    shortDescription: "Dramatic glass showcase wall for a craft brewery taproom and production space.",
    category: "commercial",
    client: "Northern Hops Brewing Co.",
    location: "Barrie, Ontario",
    completionDate: "2025-01",
    duration: "3 weeks",
    productsUsed: ["Industrial Safety Glass", "Commercial Storefront System"],
    images: ["/images/projects/brewery-1.jpg", "/images/projects/brewery-2.jpg"],
    tags: ["brewery", "showcase", "custom-glass", "hospitality"],
    isFeatured: false,
    testimonial: {
      quote: "The glass wall is the centerpiece of our taproom. Customers love watching the brewing process!",
      author: "Mark Sullivan",
      role: "Owner, Northern Hops"
    }
  },
  {
    id: "8",
    title: "GreenTech Data Center",
    description: "Specialized glass installation for a Tier 3 data center. Installed fire-rated observation panels, blast-resistant entry vestibules, and UV-blocking glass for server room corridors. All installations met the stringent security and fire safety requirements of data center operations.",
    shortDescription: "Specialized fire-rated and security glass for a Tier 3 data center facility.",
    category: "industrial",
    client: "GreenTech Solutions",
    location: "Markham, Ontario",
    completionDate: "2024-11",
    duration: "4 weeks",
    productsUsed: ["Industrial Safety Glass", "Commercial Entry Systems"],
    squareFootage: "12,000 sq ft",
    images: ["/images/projects/datacentre-1.jpg", "/images/projects/datacentre-2.jpg"],
    tags: ["data-center", "security", "fire-rated", "specialized"],
    isFeatured: false,
  },
]

export const companyInfo = {
  name: "VERREX",
  tagline: "Premium Windows & Doors",
  description:
    "VERREX is a premier window and door corporation providing high-performance fenestration systems for residential, commercial, institutional, and industrial clients. From project planning to professional installation, we deliver excellence at every step.",
  phone: "(416) 555-0199",
  email: "info@verrex.com",
  address: "123 Glass Avenue, Toronto, ON M5V 3A8",
  hours: {
    weekdays: "8:00 AM - 6:00 PM",
    saturday: "9:00 AM - 4:00 PM",
    sunday: "Closed",
  },
  social: {
    facebook: "#",
    instagram: "#",
    linkedin: "#",
    twitter: "#",
  },
}
