import { Product, Service, Testimonial, Partner, Project } from "@/types"

export const products: Product[] = [
  {
    id: "top-hung",
    name: "Top Hung (Awning) Window",
    description: "Top-hinged window that swings outward from the bottom. Excellent for ventilation while maintaining weather protection. The outward swing prevents rain from entering even when open. Ideal for bathrooms, kitchens, and basements where moisture control and airflow are essential.",
    shortDescription: "Top-hinged awning window — ventilates while keeping rain out.",
    category: "residential",
    subcategory: "Windows",
    diagramId: "double-hung",
    images: [],
    features: ["Opens outward from bottom", "Rain protection while ventilating", "Multi-point locking system", "Excellent seal performance", "Easy to operate", "Low maintenance"],
    specifications: { "Frame": "Aluminum / PVC", "Glass": "Double or Triple Glazed", "Operation": "Top-hinged, swings outward", "Rating": "CSA A440", "Energy": "ENERGY STAR® Certified" },
    priceRange: { min: 300, max: 1100 },
    isCustomizable: true,
    isFeatured: true,
    tags: ["awning", "ventilation", "residential", "bathroom", "kitchen"]
  },
  {
    id: "sliding-window",
    name: "Sliding Window",
    description: "Horizontal sliding window with smooth glide operation. One or more sashes slide laterally along tracks, providing wide opening areas without protruding outside. Perfect for spaces where outward-opening windows are impractical, such as near walkways, patios, or tight exterior spaces.",
    shortDescription: "Smooth horizontal sliding window — wide openings, space-efficient.",
    category: "residential",
    subcategory: "Windows",
    diagramId: "sliding",
    images: [],
    features: ["Smooth horizontal glide", "No exterior protrusion", "Wide opening area", "Easy to clean", "Durable track system", "Screen compatible"],
    specifications: { "Frame": "Aluminum / PVC", "Glass": "Double or Triple Glazed", "Operation": "Horizontal slide", "Rating": "CSA A440", "Energy": "ENERGY STAR® Certified" },
    priceRange: { min: 250, max: 900 },
    isCustomizable: true,
    isFeatured: false,
    tags: ["sliding", "horizontal", "residential", "patio", "space-saving"]
  },
  {
    id: "casement",
    name: "Casement Window",
    description: "Side-hinged window that swings outward with a crank or lever handle. Provides maximum ventilation and unobstructed views when fully open. The compression seal creates an airtight fit when closed, making casement windows among the most energy-efficient options available.",
    shortDescription: "Side-hinged crank-open window — maximum airflow and energy efficiency.",
    category: "residential",
    subcategory: "Windows",
    diagramId: "casement",
    images: [],
    features: ["Full opening for maximum airflow", "Superior energy efficiency", "Compression seal when closed", "Unobstructed views", "Easy crank operation", "Multi-point locking"],
    specifications: { "Frame": "Aluminum / PVC", "Glass": "Double or Triple Glazed", "Operation": "Side-hinged, crank or lever", "Rating": "CSA A440", "Energy": "ENERGY STAR® Certified" },
    priceRange: { min: 350, max: 1200 },
    isCustomizable: true,
    isFeatured: true,
    tags: ["casement", "crank", "residential", "energy-efficient", "ventilation"]
  },
  {
    id: "tilt-turn",
    name: "Tilt & Turn Window",
    description: "European-style dual-function window that tilts inward from the top for secure ventilation or swings fully inward from the side for easy cleaning and maximum airflow. The most versatile window type available, combining safety, convenience, and superior thermal performance in one unit.",
    shortDescription: "Dual-function European window — tilts for ventilation, turns for full opening.",
    category: "residential",
    subcategory: "Windows",
    diagramId: "tilt-turn",
    images: [],
    features: ["Dual tilt and turn operation", "Inward opening for easy cleaning", "Secure tilt ventilation mode", "Superior thermal insulation", "Multi-point locking system", "European engineering"],
    specifications: { "Frame": "Aluminum / PVC", "Glass": "Double or Triple Glazed", "Operation": "Tilt-in or swing-in", "Rating": "CSA A440", "Energy": "ENERGY STAR® Certified" },
    priceRange: { min: 450, max: 1500 },
    isCustomizable: true,
    isFeatured: true,
    tags: ["tilt-turn", "european", "dual-function", "residential", "versatile"]
  },
  {
    id: "hand-cranked",
    name: "Hand Cranked (Crank-Out) Window",
    description: "Casement-style window with a precision worm-gear crank mechanism for effortless operation. The mechanical advantage of the crank makes it ideal for hard-to-reach locations like above countertops or sinks. Opens smoothly with minimal effort and locks securely in any position.",
    shortDescription: "Precision crank mechanism — effortless operation for hard-to-reach spots.",
    category: "residential",
    subcategory: "Windows",
    diagramId: "hand-cranked",
    images: [],
    features: ["Worm-gear crank mechanism", "Effortless operation", "Ideal for hard-to-reach locations", "Locks in any position", "Smooth precision movement", "Weather-tight seal"],
    specifications: { "Frame": "Aluminum / PVC", "Glass": "Double or Triple Glazed", "Operation": "Crank-out (worm gear)", "Rating": "CSA A440", "Energy": "ENERGY STAR® Certified" },
    priceRange: { min: 400, max: 1300 },
    isCustomizable: true,
    isFeatured: false,
    tags: ["hand-cranked", "crank-out", "residential", "kitchen", "above-counter"]
  },
  {
    id: "sliding-door",
    name: "Sliding Patio Door",
    description: "Premium floor-to-ceiling glass sliding door system with heavy-duty roller mechanism. Provides seamless indoor-outdoor transitions with expansive glass panels that flood interiors with natural light. Available in 2, 3, or 4-panel configurations with low-profile threshold for accessibility.",
    shortDescription: "Floor-to-ceiling glass sliding door — seamless indoor-outdoor living.",
    category: "residential",
    subcategory: "Doors",
    diagramId: "sliding-door",
    images: [],
    features: ["Heavy-duty roller mechanism", "Floor-to-ceiling glass", "Low-profile threshold", "Multi-panel configurations", "Thermal break technology", "Security locking system"],
    specifications: { "Frame": "Aluminum / PVC", "Glass": "Double or Triple Glazed", "Operation": "Horizontal slide on track", "Panels": "2, 3, or 4-panel", "Rating": "CSA A440" },
    priceRange: { min: 800, max: 3500 },
    isCustomizable: true,
    isFeatured: true,
    tags: ["sliding-door", "patio", "residential", "glass-door", "outdoor-living"]
  },
  {
    id: "folding-door",
    name: "Folding (Bi-Fold) Door",
    description: "Multi-panel bi-fold door system that accordion-folds to create wide, unobstructed openings. Panels fold neatly to one or both sides, transforming walls into open-air passages. Perfect for connecting living spaces to patios, decks, or outdoor entertaining areas.",
    shortDescription: "Bi-fold accordion door — transforms walls into wide-open passages.",
    category: "residential",
    subcategory: "Doors",
    diagramId: "folding-door",
    images: [],
    features: ["Accordion bi-fold operation", "Wide unobstructed openings", "Folds to one or both sides", "Indoor-outdoor transformation", "Heavy-duty pivot hinges", "Flush floor track option"],
    specifications: { "Frame": "Aluminum", "Glass": "Double or Triple Glazed", "Operation": "Bi-fold accordion", "Panels": "3 to 7-panel", "Rating": "CSA A440" },
    priceRange: { min: 2000, max: 8000 },
    isCustomizable: true,
    isFeatured: false,
    tags: ["folding-door", "bi-fold", "residential", "patio", "wide-opening"]
  },
  {
    id: "swing-door",
    name: "Swing Entry Door",
    description: "Commercial-grade glass swing door with push bar hardware, reinforced frame, and integrated closer mechanism. Designed for high-traffic entries with ADA-compliant threshold, panic hardware compatibility, and impact-resistant tempered glass. Available in single or double-leaf configurations.",
    shortDescription: "Commercial glass entry door — high-traffic, ADA-compliant.",
    category: "commercial",
    subcategory: "Doors",
    diagramId: "swing-door",
    images: [],
    features: ["Push bar hardware", "Integrated door closer", "ADA-compliant threshold", "Impact-resistant glass", "Panic hardware compatible", "Single or double-leaf"],
    specifications: { "Frame": "Aluminum", "Glass": "Tempered Safety Glass", "Operation": "Swing (push/pull)", "Hardware": "Commercial grade", "Rating": "CSA A440" },
    priceRange: { min: 1500, max: 5000 },
    isCustomizable: true,
    isFeatured: false,
    tags: ["swing-door", "commercial", "entry", "glass-door", "high-traffic"]
  },
]

export const services: Service[] = [
  {
    id: "1",
    name: "Free Consultation",
    description:
      "Start your project with a complimentary consultation. Our experts will discuss your vision, assess your needs, and recommend the best solutions for your space. Available in-person or via video call.",
    icon: "MessageSquare",
    type: "consultation",
    features: [
      "No-obligation assessment",
      "Expert recommendations",
      "In-person or virtual options",
      "Project timeline overview",
      "Budget guidance",
    ],
    estimatedDuration: "30-60 minutes",
  },
  {
    id: "2",
    name: "On-Site Measurement",
    description:
      "Our certified technicians visit your location to take precise measurements ensuring a perfect fit. We use laser measuring technology for accuracy down to 1/16 of an inch.",
    icon: "Ruler",
    type: "measurement",
    features: [
      "Laser precision measuring",
      "Certified technicians",
      "Same-day scheduling available",
      "Digital measurement reports",
      "Photo documentation",
    ],
    estimatedDuration: "1-2 hours",
  },
  {
    id: "3",
    name: "Professional Installation",
    description:
      "Our experienced installation team ensures your windows and doors are installed correctly, efficiently, and to the highest standards. All installations come with our satisfaction guarantee.",
    icon: "Wrench",
    type: "installation",
    features: [
      "Licensed & insured installers",
      "Clean-up included",
      "Warranty on workmanship",
      "Code compliant installation",
      "Post-installation inspection",
    ],
    estimatedDuration: "Half day - Multiple days",
  },
  {
    id: "4",
    name: "Site Inspection",
    description:
      "Comprehensive on-site inspection to evaluate existing windows, identify issues, and assess the scope of replacement or repair needs. Detailed reports provided.",
    icon: "Search",
    type: "inspection",
    features: [
      "Detailed condition assessment",
      "Energy efficiency evaluation",
      "Code compliance review",
      "Written inspection report",
      "Repair vs. replace recommendations",
    ],
    estimatedDuration: "1-3 hours",
  },
  {
    id: "5",
    name: "Custom Fabrication",
    description:
      "Need something unique? We offer custom glass cutting, shaping, and fabrication to meet your exact specifications. From decorative glass to specialty shapes, we can create it.",
    icon: "Sparkles",
    type: "custom",
    features: [
      "Custom shapes & sizes",
      "Decorative glass options",
      "Specialty coatings",
      "CAD design support",
      "Prototype development",
    ],
    estimatedDuration: "2-4 weeks",
  },
  {
    id: "6",
    name: "Repair & Maintenance",
    description:
      "Keep your windows and doors in optimal condition with our repair and maintenance services. From seal replacements to hardware repairs, we handle it all.",
    icon: "Settings",
    type: "repair",
    features: [
      "Seal replacement",
      "Hardware repair",
      "Glass replacement",
      "Weather stripping",
      "Emergency service available",
    ],
    estimatedDuration: "1-4 hours",
  },
]

export const testimonials: Testimonial[] = [
  {
    id: "1",
    name: "Sarah Mitchell",
    role: "Homeowner",
    content:
      "VEREX transformed our home with beautiful new windows. The team was professional from the initial consultation through installation. Our energy bills have dropped significantly!",
    rating: 5,
  },
  {
    id: "2",
    name: "James Rodriguez",
    role: "Property Manager",
    company: "Pinnacle Properties",
    content:
      "We've used VEREX for multiple commercial projects. Their storefront systems are top-quality and their installation team is the best in the business. Highly recommend for any commercial glazing needs.",
    rating: 5,
  },
  {
    id: "3",
    name: "Emily Chen",
    role: "Architect",
    company: "Chen & Associates",
    content:
      "As an architect, I'm very particular about the products I specify. VEREX consistently delivers high-quality window and door solutions that meet our design requirements and exceed performance expectations.",
    rating: 5,
  },
  {
    id: "4",
    name: "Michael Thompson",
    role: "Factory Manager",
    company: "Thompson Manufacturing",
    content:
      "The industrial safety glass VEREX installed in our facility has been outstanding. Their team understood our safety requirements and delivered a solution that keeps our workers protected.",
    rating: 5,
  },
]

export const partners: Partner[] = [
  {
    id: "1",
    name: "Home Depot",
    logo: "/images/partners/hd-a.svg",
    description: "Leading home improvement retailer and trusted partner.",
    website: "https://www.homedepot.ca",
    type: "affiliate",
  },
  {
    id: "2",
    name: "Home Depot Pro",
    logo: "/images/partners/hd-b.svg",
    description: "Professional-grade solutions for contractors and builders.",
    website: "https://www.homedepot.ca/pro",
    type: "affiliate",
  },
]

export const appointmentTimeSlots = [
  "9:00 AM",
  "9:30 AM",
  "10:00 AM",
  "10:30 AM",
  "11:00 AM",
  "11:30 AM",
  "1:00 PM",
  "1:30 PM",
  "2:00 PM",
  "2:30 PM",
  "3:00 PM",
  "3:30 PM",
  "4:00 PM",
]

export const projects: Project[] = [
  {
    id: "1",
    title: "Lakeside Luxury Residence",
    description: "Complete window replacement for a 5,000 sq ft lakefront property. Installed 32 custom casement and picture windows with triple-pane glass for maximum energy efficiency and noise reduction. The project included custom-matched wood interior trim and exterior aluminum cladding in a bronze finish.",
    shortDescription: "Full window replacement for a premium lakefront estate with custom triple-pane glass.",
    category: "residential",
    client: "The Morrison Family",
    location: "Muskoka, Ontario",
    completionDate: "2025-11",
    duration: "3 weeks",
    productsUsed: ["Casement Windows", "Double Hung Windows"],
    squareFootage: "5,000 sq ft",
    images: ["/images/projects/lakeside-1.jpg", "/images/projects/lakeside-2.jpg"],
    tags: ["luxury", "lakefront", "energy-efficient", "custom"],
    isFeatured: true,
    testimonial: {
      quote: "VEREX transformed our lake house. The new windows are stunning and our heating bills dropped by 40%.",
      author: "Robert Morrison",
      role: "Homeowner"
    }
  },
  {
    id: "2",
    title: "Pinnacle Tower Storefront",
    description: "Design and installation of a complete commercial storefront system for a 12-story mixed-use building in downtown Toronto. The project featured thermally-broken aluminum framing, structural glazing, and integrated automatic entry systems. Completed on schedule despite challenging urban logistics.",
    shortDescription: "Full commercial storefront and entry system for a landmark downtown tower.",
    category: "commercial",
    client: "Pinnacle Properties Inc.",
    location: "Toronto, Ontario",
    completionDate: "2025-09",
    duration: "6 weeks",
    productsUsed: ["Commercial Storefront System", "Commercial Entry Systems"],
    squareFootage: "8,500 sq ft glass",
    images: ["/images/projects/pinnacle-1.jpg", "/images/projects/pinnacle-2.jpg"],
    tags: ["storefront", "high-rise", "downtown", "automatic-doors"],
    isFeatured: true,
    testimonial: {
      quote: "The VEREX team delivered a world-class storefront that sets our building apart. Professional from start to finish.",
      author: "James Rodriguez",
      role: "Property Manager, Pinnacle Properties"
    }
  },
  {
    id: "3",
    title: "Heritage Home Restoration",
    description: "Meticulous restoration of original-style windows in a heritage-designated Victorian home. Created custom wood-frame double hung windows with period-accurate grid patterns while incorporating modern Low-E glass and weatherstripping for 21st-century performance.",
    shortDescription: "Period-accurate window restoration for a heritage Victorian home with modern performance.",
    category: "residential",
    client: "Dr. Elena Vasquez",
    location: "Kingston, Ontario",
    completionDate: "2025-07",
    duration: "4 weeks",
    productsUsed: ["Double Hung Windows"],
    squareFootage: "3,200 sq ft",
    images: ["/images/projects/heritage-1.jpg", "/images/projects/heritage-2.jpg"],
    tags: ["heritage", "restoration", "victorian", "custom-grilles"],
    isFeatured: true,
    testimonial: {
      quote: "They preserved the character of our 1890s home while making it comfortable for modern living. True craftsmen.",
      author: "Dr. Elena Vasquez",
      role: "Homeowner"
    }
  },
  {
    id: "4",
    title: "AutoTech Manufacturing Facility",
    description: "Comprehensive safety glass installation for a 45,000 sq ft automotive parts manufacturing plant. Installed fire-rated glass partitions, blast-resistant observation windows, and industrial overhead doors with full-view glass panels. All installations met strict OH&S and National Building Code of Canada requirements.",
    shortDescription: "Industrial safety glass and fire-rated partitions for a major manufacturing plant.",
    category: "industrial",
    client: "AutoTech Manufacturing",
    location: "Oshawa, Ontario",
    completionDate: "2025-06",
    duration: "5 weeks",
    productsUsed: ["Industrial Safety Glass", "Industrial Overhead Doors"],
    squareFootage: "45,000 sq ft",
    images: ["/images/projects/autotech-1.jpg", "/images/projects/autotech-2.jpg"],
    tags: ["safety-glass", "fire-rated", "manufacturing", "industrial"],
    isFeatured: false,
    testimonial: {
      quote: "Safety is our top priority. VEREX delivered door systems that exceed our safety requirements.",
      author: "Michael Thompson",
      role: "Factory Manager"
    }
  },
  {
    id: "5",
    title: "Skyline Office Complex",
    description: "Designed and installed a unitized curtain wall system for a new 8-story office complex. The project featured solar control glass, acoustic insulation panels, and a dramatic double-height lobby glazing. BIM coordination ensured seamless integration with the building envelope.",
    shortDescription: "Modern curtain wall system for a prestigious 8-story office development.",
    category: "commercial",
    client: "Skyline Developments",
    location: "Vancouver, British Columbia",
    completionDate: "2025-04",
    duration: "10 weeks",
    productsUsed: ["Curtain Wall System", "Commercial Entry Systems"],
    squareFootage: "22,000 sq ft glass",
    images: ["/images/projects/skyline-1.jpg", "/images/projects/skyline-2.jpg"],
    tags: ["curtain-wall", "office", "high-performance", "BIM"],
    isFeatured: true,
  },
  {
    id: "6",
    title: "Riverside Condo Conversions",
    description: "Window and patio door replacement across 48 units in a riverside condominium complex. Coordinated with the condo board and residents for minimal disruption. Each unit received custom-sized sliding patio doors and energy-efficient casement windows.",
    shortDescription: "Multi-unit window & patio door upgrade for a 48-unit riverside condominium.",
    category: "residential",
    client: "Riverside Condo Corp. #412",
    location: "Ottawa, Ontario",
    completionDate: "2025-03",
    duration: "8 weeks",
    productsUsed: ["Sliding Patio Doors", "Casement Windows"],
    squareFootage: "48 units",
    images: ["/images/projects/riverside-1.jpg", "/images/projects/riverside-2.jpg"],
    tags: ["multi-unit", "condo", "patio-doors", "bulk-project"],
    isFeatured: false,
  },
  {
    id: "7",
    title: "Craft Brewery Showcase",
    description: "Custom glass installation for a craft brewery taproom and production facility. Featured a dramatic floor-to-ceiling glass wall separating the brewing area from the tasting room, giving patrons a full view of the brewing process while maintaining climate control.",
    shortDescription: "Dramatic glass showcase wall for a craft brewery taproom and production space.",
    category: "commercial",
    client: "Northern Hops Brewing Co.",
    location: "Calgary, Alberta",
    completionDate: "2025-01",
    duration: "3 weeks",
    productsUsed: ["Industrial Safety Glass", "Commercial Storefront System"],
    images: ["/images/projects/brewery-1.jpg", "/images/projects/brewery-2.jpg"],
    tags: ["brewery", "showcase", "custom-glass", "hospitality"],
    isFeatured: false,
    testimonial: {
      quote: "The glass wall is the centerpiece of our taproom. Customers love watching the brewing process!",
      author: "Mark Sullivan",
      role: "Owner, Northern Hops"
    }
  },
  {
    id: "8",
    title: "GreenTech Data Center",
    description: "Specialized glass installation for a Tier 3 data center. Installed fire-rated observation panels, blast-resistant entry vestibules, and UV-blocking glass for server room corridors. All installations met the stringent security and fire safety requirements of data center operations.",
    shortDescription: "Specialized fire-rated and security glass for a Tier 3 data center facility.",
    category: "industrial",
    client: "GreenTech Solutions",
    location: "Montreal, Quebec",
    completionDate: "2024-11",
    duration: "4 weeks",
    productsUsed: ["Industrial Safety Glass", "Commercial Entry Systems"],
    squareFootage: "12,000 sq ft",
    images: ["/images/projects/datacentre-1.jpg", "/images/projects/datacentre-2.jpg"],
    tags: ["data-center", "security", "fire-rated", "specialized"],
    isFeatured: false,
  },
]

export const companyInfo = {
  name: "VEREX",
  tagline: "Premium Windows & Doors",
  description:
    "VEREX is a premier window and door corporation providing high-performance fenestration systems for residential, commercial, institutional, and industrial clients across Canada. From project planning to professional installation, we deliver excellence at every step.",
  phone: "(514) 742-2160",
  email: "admin@verex.ca",
  address: "123 Glass Avenue, Toronto, ON M5V 3A8",
  hours: {
    weekdays: "8:00 AM - 6:00 PM",
    saturday: "9:00 AM - 4:00 PM",
    sunday: "Closed",
  },
  social: {
    facebook: "#",
    instagram: "#",
    linkedin: "#",
    twitter: "#",
  },
}
