const fs = require('fs');
const path = require('path');

const en = {
  "Navigation": {
    "home": "Home",
    "products": "Products",
    "residential": "Residential",
    "commercial": "Commercial",
    "industrial": "Industrial",
    "windowTypes": "Window Types",
    "catalog": "Catalog",
    "projects": "Projects",
    "services": "Services",
    "about": "About",
    "contact": "Contact",
    "getQuote": "Get a Quote",
    "bookAppointment": "Book Appointment",
    "searchPlaceholder": "Search...",
    "searchFullPlaceholder": "Search products, services, team...",
    "verrex": "VERREX",
    "windowsAndDoors": "Windows & Doors",
    "monFri": "Mon-Fri: ",
    "callUs": "Call Us",
    "search": "Search"
  },
  "Footer": {
    "products": "Products",
    "services": "Services",
    "company": "Company",
    "residentialWindows": "Residential Windows",
    "commercialGlass": "Commercial Glass",
    "industrialSolutions": "Industrial Solutions",
    "allProducts": "All Products",
    "freeConsultation": "Free Consultation",
    "onSiteMeasurement": "On-Site Measurement",
    "professionalInstallation": "Professional Installation",
    "repairMaintenance": "Repair & Maintenance",
    "aboutUs": "About Us",
    "contactLink": "Contact",
    "partners": "Partners",
    "careers": "Careers",
    "description": "Premium window and door solutions for residential, commercial, and industrial projects across Canada.",
    "allRightsReserved": "All rights reserved.",
    "premiumWindows": "Premium Windows & Doors"
  },
  "MobileActionBar": {
    "home": "Home",
    "products": "Products",
    "quote": "Quote",
    "call": "Call",
    "menu": "Menu"
  },
  "HomePage": {
    "badge": "Premium Windows & Doors",
    "heroTitle": "Engineered for",
    "heroTitleGradient": "Every Project",
    "heroDescription": "VERREX delivers high-performance window and door systems for residential, commercial, institutional, and industrial projects. Trusted by developers, architects, and facility managers across Canada.",
    "viewCatalog": "View Product Catalog",
    "bookConsultation": "Book Consultation",
    "heroAlt": "VERREX premium window and door systems",
    "stat1Value": "500+",
    "stat1Label": "Projects Delivered",
    "stat2Value": "2M+",
    "stat2Label": "Sq Ft Installed",
    "stat3Value": "98%",
    "stat3Label": "On-Time Completion",
    "stat4Value": "15+",
    "stat4Label": "Years in Industry",
    "cert1": "CSA A440 Certified",
    "cert2": "NAFS Rated",
    "cert3": "ENERGY STAR\u00ae Canada",
    "cert4": "FenestrationCanada",
    "categoryResidential": "Residential & Multi-Family",
    "categoryResidentialDesc": "Energy-efficient window and door systems for homes, condominiums, and multi-unit developments.",
    "categoryCommercial": "Commercial & Institutional",
    "categoryCommercialDesc": "Storefront systems, curtain walls, and entry doors for offices, government buildings, and retail.",
    "categoryIndustrial": "Industrial & Manufacturing",
    "categoryIndustrialDesc": "Heavy-duty fire-rated doors, safety glazing, and high-performance systems for industrial facilities.",
    "exploreProducts": "Explore Products",
    "featuredProducts": "Featured Products",
    "featuredProductsDesc": "Discover our most popular window and door systems.",
    "featured": "Featured",
    "from": "From",
    "viewDetails": "View Details",
    "viewAllProducts": "View All Products",
    "ourServices": "Our Services",
    "ourServicesDesc": "Comprehensive window and door solutions from consultation to installation.",
    "learnMore": "Learn More",
    "viewAllServices": "View All Services",
    "recentProjects": "Recent Projects",
    "recentProjectsDesc": "Explore our latest completed installations.",
    "client": "Client",
    "viewProject": "View Project",
    "viewAllProjects": "View All Projects",
    "trustedPartners": "Trusted Partners",
    "trustedPartnersDesc": "We work with industry-leading manufacturers and suppliers.",
    "manufacturer": "Manufacturer",
    "partner": "Partner",
    "whatClientsSay": "What Our Clients Say",
    "whatClientsSayDesc": "Hear from our satisfied customers across Canada.",
    "ctaTitle": "Ready to Start Your Project?",
    "ctaDesc": "Get a free consultation and quote for your window and door needs.",
    "getFreeQuote": "Get Free Quote",
    "contactUs": "Contact Us",
    "quickQuote": "Quick Quote",
    "quickQuoteDesc": "Get a fast estimate for your project",
    "fullName": "Full Name",
    "email": "Email",
    "phone": "Phone",
    "projectType": "Project Type",
    "selectType": "Select type...",
    "residentialOption": "Residential",
    "commercialOption": "Commercial",
    "industrialOption": "Industrial",
    "getEstimate": "Get Estimate",
    "quoteFormTitle": "Premium Windows & Doors",
    "quoteFormSubtitle": "Get a Free Quote"
  },
  "AboutPage": {
    "title": "About VERREX",
    "description": "Learn about our commitment to delivering premium fenestration solutions across Canada.",
    "missionTitle": "Our Mission",
    "missionText1": "VERREX is a premier window and door corporation delivering high-performance fenestration systems for residential, commercial, institutional, and industrial projects.",
    "missionText2": "With over 15 years of experience, we have built a reputation for quality craftsmanship, reliable service, and innovative solutions. Our team works closely with architects, developers, contractors, and homeowners to deliver exceptional results on every project.",
    "licensedInsured": "Licensed & Insured",
    "qualityCertified": "Quality Certified",
    "expertTeam": "Expert Team",
    "clientFocused": "Client Focused",
    "coreValues": "Core Values",
    "qualityTitle": "Quality",
    "qualityDesc": "We never compromise on quality. Every product we install meets the highest industry standards and certifications.",
    "integrityTitle": "Integrity",
    "integrityDesc": "Honest communication, transparent pricing, and reliable timelines are the foundation of every client relationship.",
    "innovationTitle": "Innovation",
    "innovationDesc": "We stay at the forefront of fenestration technology, offering the latest in energy efficiency and design.",
    "serviceTitle": "Service",
    "serviceDesc": "From initial consultation to post-installation support, we provide exceptional service at every step.",
    "ourTeam": "Our Team",
    "teamDesc": "Meet the professionals behind VERREX.",
    "partnersTitle": "Partners & Affiliates",
    "partnersDesc": "We collaborate with industry-leading manufacturers and organizations.",
    "ctaTitle": "Ready to Work With Us?",
    "ctaDesc": "Contact us to discuss your next window and door project.",
    "contactUsBtn": "Contact Us",
    "getQuoteBtn": "Get a Quote"
  },
  "AppointmentsPage": {
    "title": "Book an Appointment",
    "description": "Schedule a consultation, measurement, or showroom visit with our team.",
    "successTitle": "Appointment Booked!",
    "successDesc": "We will confirm your appointment shortly. You will receive a confirmation email with all the details.",
    "bookAnother": "Book Another Appointment",
    "selectType": "Select Appointment Type",
    "onSiteMeasurement": "On-Site Measurement",
    "onSiteMeasurementDesc": "Professional measurement at your location",
    "virtualConsultation": "Virtual Consultation",
    "virtualConsultationDesc": "Video call with our experts",
    "showroomVisit": "Showroom Visit",
    "showroomVisitDesc": "Visit our showroom in person",
    "selectDateAndTime": "Select Date & Time",
    "availableTimeSlots": "Available Time Slots",
    "yourInformation": "Your Information",
    "fullName": "Full Name",
    "fullNamePlaceholder": "John Doe",
    "email": "Email Address",
    "emailPlaceholder": "john@example.com",
    "phone": "Phone Number",
    "phonePlaceholder": "(416) 555-0100",
    "notes": "Additional Notes",
    "notesPlaceholder": "Tell us about your project...",
    "bookAppointment": "Book Appointment",
    "officeHours": "Office Hours",
    "monFri": "Monday - Friday",
    "monFriHours": "8:00 AM - 6:00 PM",
    "saturday": "Saturday",
    "saturdayHours": "9:00 AM - 4:00 PM",
    "sunday": "Sunday",
    "sundayHours": "Closed",
    "needHelp": "Need Help?",
    "callUs": "Call us at",
    "phoneNumber": "(416) 555-0199"
  },
  "CatalogPage": {
    "title": "Product Catalog",
    "supplier": "Enggia 2025",
    "description": "Browse our complete supplier catalog featuring premium windows, doors, and fenestration systems. 98 pages of products and specifications.",
    "grid": "Grid",
    "reader": "Reader",
    "pagesInfo": "{count} pages \u2022 Click any page to view full size",
    "catalogPageAlt": "Catalog page {page}",
    "pageIndicator": "Page {current} / {total}",
    "pageOf": "Page {current} of {total}",
    "interestedTitle": "Interested in Something?",
    "interestedDesc": "Contact us to get a quote on any product from our catalog.",
    "getQuote": "Get a Quote",
    "contactUs": "Contact Us",
    "bookConsultation": "Book Consultation"
  },
  "ContactPage": {
    "title": "Contact Us",
    "description": "Get in touch with our team for quotes, consultations, or any questions about our products and services.",
    "successTitle": "Message Sent!",
    "successDesc": "Thank you for reaching out. Our team will get back to you within 24 hours.",
    "sendAnother": "Send Another Message",
    "sendMessage": "Send Us a Message",
    "fullName": "Full Name",
    "fullNamePlaceholder": "John Doe",
    "email": "Email Address",
    "emailPlaceholder": "john@example.com",
    "phone": "Phone Number",
    "phonePlaceholder": "(416) 555-0100",
    "subject": "Subject",
    "subjectPlaceholder": "How can we help?",
    "message": "Message",
    "messagePlaceholder": "Tell us about your project or question...",
    "submitBtn": "Send Message",
    "getInTouch": "Get in Touch",
    "visitUs": "Visit Us",
    "address": "1234 Industrial Parkway, Unit 5-6, Toronto, ON M1P 4R7",
    "callUs": "Call Us",
    "mainPhone": "(416) 555-0199",
    "tollFree": "1-800-555-0199",
    "emailUs": "Email Us",
    "generalEmail": "info@verrex.com",
    "salesEmail": "sales@verrex.com",
    "businessHours": "Business Hours",
    "monFri": "Monday - Friday: 8:00 AM - 6:00 PM",
    "saturday": "Saturday: 9:00 AM - 4:00 PM",
    "sunday": "Sunday: Closed",
    "followUs": "Follow Us"
  },
  "SearchPage": {
    "title": "Search",
    "placeholder": "Search products, services, projects...",
    "noResults": "No results found",
    "noResultsDesc": "Try different keywords or browse our sections.",
    "browseProducts": "Browse Products",
    "browseServices": "Browse Services",
    "resultsFor": "Results for",
    "products": "Products",
    "servicesSection": "Services",
    "projectsSection": "Projects",
    "viewDetails": "View Details",
    "learnMore": "Learn More",
    "viewProject": "View Project"
  },
  "ProductsPage": {
    "title": "Our Products",
    "description": "Browse our comprehensive catalog of premium windows, doors, and door systems for residential, commercial, and industrial projects.",
    "allProducts": "All Products",
    "residential": "Residential",
    "commercial": "Commercial",
    "industrial": "Industrial",
    "searchPlaceholder": "Search products...",
    "showing": "Showing {filtered} of {total} products",
    "featured": "Featured",
    "productImage": "Product Image",
    "customizable": "Customizable",
    "viewDetails": "View Details",
    "noProducts": "No products found",
    "noProductsDesc": "Try adjusting your search or filter criteria.",
    "clearFilters": "Clear Filters",
    "from": "From"
  },
  "ProductDetail": {
    "home": "Home",
    "products": "Products",
    "customizable": "Customizable",
    "productImage": "Product Image",
    "keyFeatures": "Key Features",
    "specifications": "Specifications",
    "requestQuote": "Request Quote",
    "bookConsultation": "Book Consultation",
    "callUs": "Or call us at (416) 555-0199",
    "relatedProducts": "Related Products",
    "from": "From",
    "viewDetails": "View Details",
    "productNotFound": "Product not found",
    "backToProducts": "Back to Products"
  },
  "WindowTypes": {
    "title": "Window Types",
    "description": "Explore our window types with interactive 3D visualization. Choose your preferred style, frame color, and glass type.",
    "configure3d": "Configure in 3D",
    "configure3dDesc": "Use our interactive 3D configurator to visualize different window styles, colors, and glass types.",
    "specifications": "Specifications",
    "windowType": "Window Type",
    "frameColor": "Frame Color",
    "glassType": "Glass Type",
    "requestQuote": "Request a Quote",
    "requestQuoteDesc": "Like what you see? Get a personalized quote for your window configuration.",
    "getQuote": "Get a Quote"
  },
  "ProjectsPage": {
    "title": "Our Portfolio",
    "completedBold": "Completed ",
    "projects": "Projects",
    "description": "Explore our portfolio of completed window and door installations across residential, commercial, and industrial sectors.",
    "allProjects": "All Projects",
    "residential": "Residential",
    "commercial": "Commercial",
    "industrial": "Industrial",
    "statsCompleted": "Projects Completed",
    "statsResidential": "Residential",
    "statsCommercial": "Commercial",
    "statsIndustrial": "Industrial",
    "featuredProjects": "Featured Projects",
    "projectImage": "Project Image",
    "featured": "Featured",
    "viewDetails": "View Details",
    "allProjectsSection": "All Projects",
    "showing": "Showing {filtered} of {total} projects",
    "client": "Client: ",
    "ctaTitle": "Want Your Project Featured Here?",
    "ctaDesc": "Let's discuss your next window and door project. Get a free consultation today.",
    "getFreeQuote": "Get Free Quote",
    "bookConsultation": "Book Consultation"
  },
  "QuotePage": {
    "title": "Request a Quote",
    "description": "Get a detailed quote for your window and door project. Fill out the form below and our team will respond within 24 hours.",
    "step1": "Contact Info",
    "step2": "Project Details",
    "step3": "Additional Info",
    "step4": "Review",
    "successTitle": "Quote Request Submitted!",
    "successDesc": "Thank you for your interest! Our team will review your request and get back to you within 24 hours with a detailed estimate.",
    "submitAnother": "Submit Another Request",
    "backToHome": "Back to Home",
    "firstName": "First Name",
    "firstNamePlaceholder": "John",
    "lastName": "Last Name",
    "lastNamePlaceholder": "Doe",
    "email": "Email",
    "emailPlaceholder": "john@example.com",
    "phone": "Phone",
    "phonePlaceholder": "(416) 555-0100",
    "company": "Company (Optional)",
    "companyPlaceholder": "Your company name",
    "projectType": "Project Type",
    "selectProjectType": "Select project type",
    "residentialOption": "Residential",
    "commercialOption": "Commercial",
    "industrialOption": "Industrial",
    "institutionalOption": "Institutional",
    "projectScope": "Project Scope",
    "selectScope": "Select scope",
    "newConstruction": "New Construction",
    "renovation": "Renovation",
    "replacement": "Replacement",
    "addition": "Addition",
    "productInterest": "Products of Interest",
    "timeline": "Preferred Timeline",
    "selectTimeline": "Select timeline",
    "urgent": "Urgent (Within 2 weeks)",
    "oneMonth": "Within 1 month",
    "threeMonths": "Within 3 months",
    "sixMonths": "Within 6 months",
    "flexible": "Flexible / Not sure",
    "budget": "Estimated Budget",
    "selectBudget": "Select budget range",
    "budgetUnder10k": "Under $10,000",
    "budget10to25k": "$10,000 - $25,000",
    "budget25to50k": "$25,000 - $50,000",
    "budget50to100k": "$50,000 - $100,000",
    "budgetOver100k": "Over $100,000",
    "additionalDetails": "Additional Details",
    "additionalDetailsPlaceholder": "Tell us more about your project...",
    "preferredContact": "Preferred Contact Method",
    "emailContact": "Email",
    "phoneContact": "Phone",
    "eitherContact": "Either",
    "reviewTitle": "Review Your Request",
    "contactInfo": "Contact Information",
    "projectDetails": "Project Details",
    "additionalInfo": "Additional Information",
    "name": "Name",
    "type": "Type",
    "scope": "Scope",
    "productsInterest": "Products",
    "timelineLabel": "Timeline",
    "budgetLabel": "Budget",
    "details": "Details",
    "contactMethod": "Contact Method",
    "back": "Back",
    "next": "Next",
    "submitRequest": "Submit Request"
  },
  "ServicesPage": {
    "title": "Our Services",
    "description": "Comprehensive window and door solutions from expert consultation to professional installation and ongoing maintenance.",
    "estimatedDuration": "Estimated Duration",
    "learnMore": "Learn More",
    "getStarted": "Get Started",
    "whyChoose": "Why Choose VERREX?",
    "whyChooseDesc": "We provide end-to-end solutions with industry-leading expertise.",
    "certifiedExperts": "Certified Experts",
    "certifiedExpertsDesc": "All our technicians are certified and trained to the highest industry standards.",
    "qualityGuarantee": "Quality Guarantee",
    "qualityGuaranteeDesc": "We stand behind our work with comprehensive warranties on all installations.",
    "timelyService": "Timely Service",
    "timelyServiceDesc": "We respect your schedule and complete projects on time, every time.",
    "ctaTitle": "Need a Custom Solution?",
    "ctaDesc": "Contact our team to discuss your specific requirements and get a tailored quote.",
    "getFreeQuote": "Get Free Quote",
    "bookConsultation": "Book Consultation"
  },
  "WindowControls": {
    "windowType": "Window Type",
    "frameColor": "Frame Color",
    "glassType": "Glass Type"
  },
  "HeroSection": {
    "home": "Home"
  },
  "Common": {
    "loading": "Loading...",
    "error": "An error occurred",
    "retry": "Retry",
    "close": "Close",
    "previous": "Previous",
    "nextLabel": "Next",
    "of": "of",
    "page": "Page"
  },
  "Data": {
    "products": {
      "casement-windows": { "name": "Casement Windows", "description": "Premium casement windows with multi-point locking systems and superior weather sealing. Ideal for residential and light commercial applications with maximum ventilation and unobstructed views.", "shortDescription": "Energy-efficient casement windows with superior ventilation and modern aesthetics." },
      "sliding-patio-doors": { "name": "Sliding Patio Doors", "description": "Smooth-operating sliding patio doors with premium rollers, multi-point locks, and thermal break frames. Perfect for connecting indoor and outdoor living spaces.", "shortDescription": "Premium sliding doors for seamless indoor-outdoor transitions." },
      "double-hung-windows": { "name": "Double Hung Windows", "description": "Classic double hung windows with tilt-in sashes for easy cleaning. Features warm edge spacers, argon gas fill, and optional grille patterns.", "shortDescription": "Traditional double hung windows with modern performance features." },
      "storefront-systems": { "name": "Storefront Systems", "description": "Commercial-grade storefront glazing systems designed for retail, office, and institutional buildings. Features thermally broken aluminum frames and high-performance glazing.", "shortDescription": "Professional storefront systems for commercial applications." },
      "curtain-wall-systems": { "name": "Curtain Wall Systems", "description": "Architectural curtain wall systems for mid-rise and high-rise buildings. Engineered for structural performance, thermal efficiency, and aesthetic excellence.", "shortDescription": "High-performance curtain wall systems for modern architecture." },
      "commercial-entry-systems": { "name": "Commercial Entry Systems", "description": "Heavy-duty commercial entry door systems with panic hardware, automatic operators, and ADA compliance. Available in aluminum, steel, and glass configurations.", "shortDescription": "Durable entry systems for commercial and institutional buildings." },
      "safety-glass-panels": { "name": "Safety Glass Panels", "description": "Industrial-grade safety glass panels including tempered, laminated, and fire-rated options. Meets all Canadian safety standards for industrial environments.", "shortDescription": "Industrial safety glass solutions for demanding environments." },
      "overhead-doors": { "name": "Overhead Doors", "description": "Heavy-duty overhead doors for warehouses, loading docks, and industrial facilities. Available in insulated, fire-rated, and high-speed configurations.", "shortDescription": "Industrial overhead doors for warehouses and facilities." }
    },
    "services": {
      "installation": { "name": "Professional Installation", "description": "Expert installation by certified technicians. We handle everything from removal of old units to final finishing and cleanup." },
      "measurement": { "name": "On-Site Measurement", "description": "Precise on-site measurements by our trained professionals to ensure perfect fit and optimal performance." },
      "inspection": { "name": "Window & Door Inspection", "description": "Comprehensive inspection services to assess the condition of existing windows and doors, with detailed reports and recommendations." },
      "consultation": { "name": "Free Consultation", "description": "Expert advice on product selection, energy efficiency, and design options. Available in-person or virtually." },
      "repair": { "name": "Repair & Maintenance", "description": "Professional repair and maintenance services to extend the life of your windows and doors. Emergency service available." },
      "custom": { "name": "Custom Design", "description": "Bespoke window and door solutions tailored to your unique architectural requirements and specifications." }
    },
    "projects": {
      "lakeside-villa": { "title": "Lakeside Villa Renovation", "description": "Complete window replacement for a luxury lakeside property featuring floor-to-ceiling casement windows and sliding patio doors.", "client": "Private Homeowner", "scope": "Full window and door replacement" },
      "pinnacle-tower": { "title": "Pinnacle Tower", "description": "Curtain wall installation for a 25-story mixed-use tower in downtown Toronto, featuring high-performance glazing.", "client": "Pinnacle Developments", "scope": "Curtain wall system installation" },
      "riverside-commons": { "title": "Riverside Commons", "description": "Multi-unit residential development with energy-efficient windows and balcony door systems for 150 units.", "client": "Riverside Development Group", "scope": "Windows and doors for 150 units" },
      "heritage-house": { "title": "Heritage House Restoration", "description": "Sensitive restoration of heritage windows with modern energy-efficient replacements that maintain the original aesthetic.", "client": "Heritage Conservation Board", "scope": "Heritage window restoration" },
      "skyline-business": { "title": "Skyline Business Centre", "description": "Commercial storefront and entry system installation for a modern office complex with automated entrance systems.", "client": "Skyline Properties", "scope": "Storefront and entry systems" },
      "autotech-manufacturing": { "title": "AutoTech Manufacturing", "description": "Industrial safety glass and overhead door installation for a large automotive manufacturing facility.", "client": "AutoTech Industries", "scope": "Safety glass and overhead doors" },
      "brewery-district": { "title": "Brewery District Lofts", "description": "Conversion of historic brewery into modern loft residences with custom industrial-style windows and doors.", "client": "Urban Revival Inc.", "scope": "Custom windows and doors for 80 units" }
    },
    "partners": {
      "premiumglass-pro": { "name": "PremiumGlass Pro", "description": "Leading manufacturer of high-performance glazing systems" },
      "thermalframe-systems": { "name": "ThermalFrame Systems", "description": "Innovative thermal break frame technology" },
      "securevision-glass": { "name": "SecureVision Glass", "description": "Specialty safety and security glass products" },
      "buildright-contractors": { "name": "BuildRight Contractors", "description": "Premier general contracting partner" },
      "archvision-design": { "name": "ArchVision Design Studio", "description": "Award-winning architectural design firm" },
      "greenbuild-consulting": { "name": "GreenBuild Consulting", "description": "Sustainable building consultants" }
    },
    "testimonials": {
      "t1": { "content": "VERREX delivered exceptional quality on our condo project. The curtain wall system exceeded our expectations in both performance and aesthetics.", "name": "David Chen", "role": "Project Manager", "company": "Pinnacle Developments" },
      "t2": { "content": "Outstanding service from start to finish. The team was professional, on time, and the installation quality is superb.", "name": "Sarah Mitchell", "role": "Homeowner", "company": "Lakeside Villa" },
      "t3": { "content": "We have used VERREX for multiple commercial projects. Their storefront systems are top-notch and their service is reliable.", "name": "Michael Torres", "role": "Facilities Director", "company": "Skyline Properties" },
      "t4": { "content": "The heritage window restoration was handled with incredible care and attention to detail. Truly impressive craftsmanship.", "name": "Elizabeth Grant", "role": "Conservation Officer", "company": "Heritage Board" },
      "t5": { "content": "Fast, professional, and high quality. VERREX installed safety glass throughout our manufacturing facility ahead of schedule.", "name": "Robert Kim", "role": "Plant Manager", "company": "AutoTech Industries" },
      "t6": { "content": "The custom window design for our brewery loft conversion was perfect. VERREX understood the industrial aesthetic we wanted.", "name": "Jessica Lavoie", "role": "Creative Director", "company": "Urban Revival Inc." },
      "t7": { "content": "Excellent energy efficiency improvements. Our heating costs dropped significantly after VERREX replaced all our windows.", "name": "Thomas Anderson", "role": "Property Manager", "company": "Riverside Commons" }
    },
    "team": {
      "member1": { "name": "Alexandra Dumont", "role": "CEO & Founder" },
      "member2": { "name": "Marcus Chen", "role": "Operations Director" },
      "member3": { "name": "Sarah Williams", "role": "Lead Designer" },
      "member4": { "name": "David Petrov", "role": "Installation Director" }
    },
    "windowTypes": { "casement": "Casement", "awning": "Awning", "fixed": "Fixed", "sliding": "Sliding", "doubleHung": "Double Hung" },
    "frameColors": { "white": "White", "black": "Black", "brown": "Brown", "gray": "Gray", "natural": "Natural Wood" },
    "glassTypes": { "clear": "Clear", "frosted": "Frosted", "tinted": "Tinted", "lowE": "Low-E", "tempered": "Tempered", "laminated": "Laminated" }
  }
};

const outDir = path.join(__dirname, '..', 'messages');
fs.writeFileSync(path.join(outDir, 'en.json'), JSON.stringify(en, null, 2));
console.log('en.json created');
